default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: password

development:
  <<: *default
  database: active-accounting-dev
test:
  <<: *default
  database: active-accounting-test

production:
  <<: *default
  database: active_accounting_production2
