angular.module('accounting.services', [
  'Devise'
  'ngRoute'
  'ngResource'
  'xeditable'
  'pascalprecht.translate'
  'ngCookies'
  'angular.filter'
  'ngAnimate'
  'mgcrea.ngStrap'
  'mgcrea.ngStrap.datepicker'
  'ui.bootstrap.buttons'
  'ui.date'
  'toggle-switch'
])
